### ISSUE TITLE
height?

### ISSUE THREAD

**Issue by A3ExilePortal** [neos7/FiveM_vstancer#1]
can we expect to see height added soon ? loving this so far

**Comment by carmineos** [comment]
That's more like a handling property, it will be included in a handling editor script, I don't think it fits good here.

**Comment by A3ExilePortal** [comment]
But that’s v Stancer camber width and height

**Comment by carmineos** [comment]
The ExtraNative to edit the height of the wheels bone hasn't been implemented in FiveM cause apparently it breaks other things. So unless FiveM manages to work around that, I won't add such a feature. If you refer to the suspension raise instead, as I said it's a handling field, so it will be editable in the handling editor.

Anyway anyone is free to edit this as prefers. There is a server which has a custom version which also allows to edit the fSteeringLock which is again a handling field.
