### ISSUE TITLE
Vstancer conflicts with NativeUI

### ISSUE THREAD

**Issue by nhudtwalcker** [neos7/FiveM_vstancer#14]
Hello,

Hoping someone can help out, I just installed this vstancer into my server but I also had a custom NativeUI menu in lua that I made and installed on my server.  The NativeUI menu worked perfect but once I installed the vstancer, my menu no longer appears.  If I remove vstancer it will work again but once I add it back the menu will no longer show up.  The menu is set to open with F7 but I also tried different keys.  I am suspecting that something with MenuAPI is conflicting with NativeUI.  Is this possible and is there a way to work around it/

Thank you

**Comment by carmineos** [comment]
Thanks for reporting it, I will look into this.

**Comment by carmineos** [comment]
@nhudtwalcker Which NativeUI version are you using?

**Comment by nhudtwalcker** [comment]
> @nhudtwalcker Which NativeUI version are you using?

@carmineos I'm using the version from this Github:
https://github.com/FrazzIe/NativeUILua

**Comment by carmineos** [comment]
> > @nhudtwalcker Which NativeUI version are you using?
> 
> @carmineos I'm using the version from this Github:
> https://github.com/FrazzIe/NativeUILua

What I think at the moment is that it's related to disabled controls.
VStancer uses MenuAPI for the UI and currently MenuAPI disables the control you bind to it as toggle menu control.
So in this case if you are using vstancer with the default control, which is 167, that will be marked as disabled.

Althought I am not sure yet if this behaviour is logically correct and/or if it can be changed (will look in it asap), assuming this is the problem, I think that if your UI library only checks for enabled controls then It will never detect it as pressed/released.

So first of all avoid using multiple UI binded to the same control, and if you really need this to be binded to the same control, try to make your UI also check for disabled controls by replacing
`IsControl*(group, control)` with `IsControl*(group, control) or IsDisabledControl*(group, control)`

Example for JustReleased state checks:
replace `IsControlJustReleased(0, 167)` with `IsControlJustReleased(0, 167) or IsDisabledControlJustReleased(0, 167)`

**Comment by carmineos** [comment]
I made a PR to MenuAPI https://github.com/TomGrobbe/MenuAPI/pull/27 I will soon update vstancer, meanwhile you could try using the latest artifact from MenuAPI and see if this still happens.

Get latest MenuAPI artifact [here](https://ci.appveyor.com/api/buildjobs/nh83386m7h7d7non/artifacts/MenuAPI-v3.1.2-FiveM.zip) and replace `MenuAPI.dll` in vstancer resource with the one from the artifact.

EDIT: A new nuget package has been pushed for MenuAPI, and latest vstancer artifact from development branch has been updated to use it.

So just get the latest artifact [here](https://ci.appveyor.com/project/carmineos/fivem-vstancer/build/artifacts)

**Comment by nhudtwalcker** [comment]
Thank you so much for your time, I will give this a shot and let you know if it works.

Thank you

**Comment by carmineos** [comment]
@nhudtwalcker Has it resolved the issue?

**Comment by nhudtwalcker** [comment]
Yes it did!! I just tried it, Thank you so much.
