### ISSUE TITLE
Menu Placement

### ISSUE THREAD

**Issue by itsHazeyo** [neos7/FiveM_vstancer#18]
Just a reminder to add the option to be able to move the vStancer menu to the left side of the screen

**Comment by carmineos** [comment]
Hi, I've just pushed an update which added such option (https://github.com/carmineos/fivem-vstancer/commit/3165839c1d523e7c0fd9e0063cf91dfbf5f816e3).
The option will now be available in the "Client Settings Menu" with [the latest artifact](https://ci.appveyor.com/project/carmineos/fivem-vstancer/branch/development/artifacts).
