### ISSUE TITLE
vStancer resource heavy.

### ISSUE THREAD

**Issue by YpsilonTM** [neos7/FiveM_vstancer#20]
vstance 1.4 also tried 2.0 are running at a pretty high resource ticks.

![image](https://user-images.githubusercontent.com/22861150/100490059-9d1f9180-3118-11eb-8505-353a28cd5423.png)

**Comment by carmineos** [comment]
That's normal, the resource edits wheels nodes transformation each tick, so it keeps scanning surrounding vehicles to update them. For now I can't really improve much the performance, but one day, once the natives to edit SubHandlingData will be available, the camber will be edited using that (which should only require to change it once), while the track width it's still not a game native thing so it will continue to be updated each tick. So hopefully cpu time might halve.

Another improvement could be to only track vehicles which have players inside, but I don't want to do that as a lot of people like to have cars parked with camber on.

**Comment by YpsilonTM** [comment]
Ah ok nice, and another thing i had to revert to 1.4 because on 2.0 only i saw the changes and other people didn't so changes were only client side.

**Comment by carmineos** [comment]
@YpsilonTM  Try downloading the 2.0 again! that's a prerelease which uses artifacts from development branch, but it was using an old artifact which had a bug in the range of the script. Now it has the latest artifact which has that bug fixed.
