### ISSUE TITLE
Widescreen aspect ratio warning spam

### ISSUE THREAD

**Issue by gegen** [neos7/FiveM_vstancer#21]
I run a widescreen monitor (almost 21:9) and my console is spammed with warnings. I tried looking into the code but only saw that the alignment is changed once. I do not have this issue with vMenu so it's probably not an issue with the MenuAPI.
![image](https://user-images.githubusercontent.com/24528238/109295644-61878700-782f-11eb-8e0d-ab7e8ac1127e.png)

**Comment by carmineos** [comment]
Seems like the script keeps trying to align to the right while MenuAPI resets it to left for the known limitation. Be sure to download latest [prelease](https://github.com/carmineos/fivem-vstancer/releases/tag/v2.0-dev) or just download the latest [development artifact](https://ci.appveyor.com/project/carmineos/fivem-vstancer/branch/development/artifacts).
Then if you check the "Menu Left Alignment" option in the Client Settings Menu it should stop spamming.

I should probably add an API to MenuAPI 
```cs
bool IsRightAlignmentSupported()
```
so it could be used in cases like mine, even if I should probably handle better this scenario

**Comment by carmineos** [comment]
@gegen I've just pushed an update, it shouldn't spam anymore now.
Download the latest [development artifact](https://ci.appveyor.com/project/carmineos/fivem-vstancer/branch/development/artifacts).
