### ISSUE TITLE
Any chance of donate to get exports for wheelsize/wheelwidth

### ISSUE THREAD

**Issue by EGUltraTM** [neos7/FiveM_vstancer#25]
Hi,

im using the exports for the stance very well now. 

I wanted to ask if there is any chance to donate some money to get exports for wheelsize/width also.

Maybe also some performance update. I dont know if its normal but for us it takes about 0.34ms.

Greetings.

**Comment by carmineos** [comment]
Hi, I've just been (and will be for the next few weeks) busy, cause I have exams in this period. There is no need to donate to let me implement such exports, I will do it as soon I have some free time. However if you want to donate and sponsor the project you can always use the paypal link I've added in the sponsor info available in the repository.

**Comment by EGUltraTM** [comment]
> 
> 
> Hi, I've just been (and will be for the next few weeks) busy, cause I have exams in this period. There is no need to donate to let me implement such exports, I will do it as soon I have some free time. However if you want to donate and sponsor the project you can always use the paypal link I've added in the sponsor info available in the repository.

Thx for the reply. 

Nice to hear. We love using it.


Onyl thing is it possible to increase the performance? atm when im alone on the server it takes 0.34ms allready.

**Comment by carmineos** [comment]
That's something I'm concerned about, the main part of the cpu-time is taken by the nature of the C# resource itself because of the AppDomain but there is of course a margin of improvement on the script side and I will look into it.

**Comment by EGUltraTM** [comment]
Nice to hear. Maybe thinking about converting it to lua would increase the performance?

**Comment by carmineos** [comment]
Maybe but the script still does some things each tick. Anyway that's not something I'm interested in, I will continue to develop this and optimize it.
