### ISSUE TITLE
Requests for the Script

### ISSUE THREAD

**Issue by Paintsmoker** [neos7/FiveM_vstancer#26]
Hey,

just found the script and played with it for a while.

Since my server is an roleplay server where I dont want anyone to be able to change their tyre width or camber anywhere and anytime. I would appreciate the feature to set one or multiple jobs that can open the menu so that I can put in the job names in the config and only these jobs can open it then.

If its already a thing in the script pls let me now.

Paintsmoker

**Comment by carmineos** [comment]
Permissions aren't implemented yet.

**Comment by Paintsmoker** [comment]
Well I'll wait then :)

**Comment by NoobySloth** [comment]
> Permissions aren't implemented yet.

Hey bud, is this something that is planned at all? Could really help out the racing scene :)

**Comment by carmineos** [comment]
That's something I want to add, but I haven't time to work on this at the moment.
