### ISSUE TITLE
Doesnt compile

### ISSUE THREAD

**Issue by George-RG** [neos7/FiveM_vstancer#28]
Tried to compile the code my self and it didn't work. The compiler (Visual Studio) finds a problem at the 43rd line of VStancer.Client.csproj  . To be clear I didn't change any of the code I just wanted to check the code myself. The error is 

Error	MSB3073	The command "if '' == '' ( 

Hope to fix it soon. Thanks in advance

**Comment by carmineos** [comment]
That's the post build event to copy the files to my local server folder.
You can safely delete lines 41, 42, 43 from VStancer.Client.csproj
https://github.com/carmineos/fivem-vstancer/blob/master/VStancer.Client/VStancer.Client.csproj#L42-L44

**Comment by George-RG** [comment]
Thanks
